### ISSUE TITLE
Forget to set the error!?

### ISSUE THREAD

**Issue by matzino** [norio-nomura/SwiftLintForXcode#1]
Hello Norio, 

sorry for making an issue but I never found an other way to ask you this. Until now I have not used your extension but I will (if my team accept that) after upgrading to Xcode 8. To understand how extensions works I look at your code to follow up an other article.

In your class SourceEditorCommand.swift you defer the completionHandler with the error, initialized one row above. But you never set this error var. In the catch block you only print the error. Maybe you forget this, or I don't see anything else!?

**Comment by norio-nomura** [comment]
Oh, I just forgot to set. 🙈
