### ISSUE TITLE
Not working because of Certificates

### ISSUE THREAD

**Issue by eMdOS** [norio-nomura/SwiftLintForXcode#2]
```
macOS-eMdOS:SwiftLintForXcode emdos$ xcodebuild -scheme SwiftLintForXcode install DSTROOT=~
Build settings from command line:
    DSTROOT = /Users/emdos

=== BUILD TARGET SwiftLintHelper OF PROJECT SwiftLintForXcode WITH CONFIGURATION Release ===

Check dependencies
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "PK9GMQ772L" with a private key was found.

** INSTALL FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
```

**Comment by zsoltbalint** [comment]
@eMdOS I've used my own certificates. I think without a binary, this project will only work if you have an own certificate.

**Comment by norio-nomura** [comment]
> I think without a binary, this project will only work if you have an own certificate.

Yes. When I opened this project, Xcode 8 was still in beta and I could not redistribute binary including beta version of Swift Standard Library.
Now, I uploaded https://github.com/norio-nomura/SwiftLintForXcode/releases/tag/0.1 that built on Xcode 8.0.

**Comment by Parsida** [comment]
Still the same.
