### ISSUE TITLE
Xcode 9 beta 4 error

### ISSUE THREAD

**Issue by vyachesIavskiy** [norio-nomura/SwiftLintForXcode#7]
I'm currently using Xcode 9 beta 4 and I got an error when I try to perform 'Run swiftlint autocorrect'. Is it connected to beta version or something else?

**Comment by norio-nomura** [comment]
As far as I tested on Xcode 9 beta 4, it works for me.
What error message is output?

**Comment by vyachesIavskiy** [comment]
<img width="1162" alt="screen shot 2017-07-27 at 7 47 07 am" src="https://user-images.githubusercontent.com/5702421/28654829-f11944e2-729f-11e7-8b77-d423402f9fe5.png">
 This is my message. Btw I tried the same on Xcode 8.3.3 and it says the same error.
Maybe it's somehow connected to the way lint installed. I have a pod and inly in one project.

**Comment by norio-nomura** [comment]
This extension depends on `/usr/local/bin/swiftlint`.
Xcode does not provide information on projects and workspaces to Source Editor Extension. So we can not use `swiftlint` installed by pod.
